from pathlib import Path
from html import escape as e
root=Path(__file__).resolve().parent.parent

def img(name,caption,kind=''):
    kind=kind.replace('dark','cutout')
    path=f'assets/{name}' if name.endswith('.svg') else f'assets/{name}.webp'
    return f'<figure class="study-image {kind}"><a href="{path}" data-zoom aria-label="Enlarge: {e(caption)}"><img src="{path}" alt="{e(caption)}" loading="lazy" decoding="async"><span class="zoom-hint" aria-hidden="true">+</span></a><figcaption>{e(caption)}</figcaption></figure>'
def gallery(items):
    return '<div class="study-gallery '+('one' if len(items)==1 else 'three' if len(items)==3 else '')+'">'+''.join(img(*i) for i in items)+'</div>'
def section(id,title,text,images,extra=[],insights=[],body=''):
    return f'<section class="study-section" id="{id}"><div class="section-opening"><h2>{title}</h2><div><p>{text}</p></div></div>'+gallery(images)+('<div class="insight-list">'+''.join(f'<article><h3>{a}</h3><p>{b}</p></article>' for a,b in insights)+'</div>' if insights else '')+body+'</section>'

projects=[dict(slug='xflare',name='XFLARE',tag='Safety equipment & interaction design',short='A connected field system for forest firefighters.',desc='A drone controller and tactical smartwatch that bring aerial intelligence directly to firefighters on the ground.',hero='visual-02-00',facts=[('Context','METU ID402 · Graduation project'),('External advisor','CES Advanced Composites & Defense Technologies Inc.'),('Scope','Hardware, interface & physical prototyping')],sections=[
('research','Information when it matters most.','Field research with a firefighter, an AKUT volunteer, a test pilot and a UAV technician revealed a recurring gap: aerial information does not always reach the people who need it. XFLARE explores a shared system for orientation, coordination and rapid response.', [('visual-04-00','Field research at a fire station','photo'),('visual-04-01','Examining equipment and attachment points in the field','photo')],[(3,'Literature research and problem framing'),(4,'Interview findings and design opportunities')],[('Direct information','Bring situational data from the drone to the crew’s own equipment.'),('Glove-friendly control','Use large physical controls and glanceable information under demanding conditions.'),('Shared awareness','Connect the aerial, control and ground layers within one proposed system.')]),
('development','Two tools. Distinct roles.','An early concept combined the watch and controller into a convertible device. Physical exploration exposed limitations, leading to separate tools: a controller for the operator and a wearable for field personnel.', [('visual-05-06','Testing the early wearable mock-up','photo'),('visual-10-01','Final controller and smartwatch physical models','photo')],[(5,'Convertible concept and initial mock-ups'),(6,'Fireground scenario and escape-route communication')],[]),
('interface','Designed for a quick glance.','High contrast, oversized targets and clear modes support use with gloves and in smoke. The controller brings together map, visual and thermal feeds; the watch keeps essential alerts and directional information close at hand.', [('visual-07-01','Controller interface: shared map and situational awareness','dark'),('visual-07-03','Controller interface: thermal imaging','dark'),('visual-07-05','Tactical smartwatch: map view','dark'),('visual-07-10','Tactical smartwatch: alerts and SOS','dark')],[(7,'Interface system, controls and information hierarchy')],[]),
('details','Built around the realities of the field.','Textured controls, a dedicated SOS button, protected charging access and attachment points translate field requirements into the product’s physical form. The technical study connects the wearable, controller and drones as one system concept.', [('visual-09-07','Drone controller: protective enclosure and carrying handles','dark'),('visual-09-04','Tactical smartwatch: retention bungees and protective housing','dark')],[(8,'Exploded views, dimensions and system diagram'),(9,'Physical controls and product details'),(10,'Physical model and prototype references')],[])
]),
dict(slug='harma',name='HARMA E-BRT',tag='Transportation & interior design',short='An electric mobility identity shaped by Ankara.',desc='A contemporary electric bus concept that connects Phrygian heritage with the everyday needs of Ankara’s passengers.',hero='visual-19-01',card='visual-19-02',facts=[('Context','METU ID401 · Team project'),('Team','Ece Akın, Emiyra Kazğı, Evren Catker'),('Scope','Vehicle identity, passenger experience & spatial planning')],sections=[
('research','Start with the journey.','Interviews with 16 users, including students, parents, older passengers and drivers, informed the design. Heavy bags, difficult boarding, crowded aisles and limited visibility became practical priorities for the vehicle’s spatial organisation.', [('visual-13-00','Benchmarking vehicle proportions, silhouettes and details')],[(14,'Literature research into bus systems'),(15,'Field research and user needs'),(16,'Route identification and selected context')],[('Make room for belongings','Dedicated backpack and luggage zones help keep circulation paths clear.'),('Support different passengers','Low-floor access, usable handrails and considered seating transitions respond to varied needs.'),('Make movement legible','Clear zoning and information support navigation through the vehicle.')]),
('development','A local identity, reinterpreted.','Phrygian forms and Anatolian monumentality provide a visual starting point. Moodboards and material studies translate that reference into a restrained geometric language for an electric vehicle.', [('visual-17-01','Phrygian references, material cues and colour studies'),('visual-17-00','Design inspiration and visual context')],[(13,'Sketch analysis and benchmarking'),(17,'Inspiration and moodboards')],[]),
('layout','A plan built around people.','Alternative layouts explore the relationship between seating, standing areas, accessibility and storage. The final arrangement brings those needs into a continuous passenger space, with dedicated areas for different travel situations.', [('visual-18-00','Exploring alternative passenger layouts'),('visual-18-02','Final passenger zoning and circulation plan')],[(18,'Layout development and finalisation'),(21,'Passenger scenario: parents with a stroller'),(22,'Passenger scenario: a student with luggage')],[]),
('details','From the street to the interior.','The exterior carries a geometric electric identity. Inside, ambient lighting, structural poles and seats with Phrygian-inspired details carry the same language through the passenger experience.', [('visual-19-02','Exterior perspective in an urban setting','photo'),('visual-20-00','Passenger seating and interior geometry','photo'),('visual-20-01','Handrails, lighting and the central aisle','photo'),('visual-20-02','Interior seating and support structures','photo')],[(19,'Exterior design details'),(20,'Interior design details')],[])
]),
dict(slug='mobile-infirmary',name='Mobile Infirmary',tag='Healthcare mobility & service spaces',short='A portable care environment for disaster zones.',desc='A mobile medical unit that expands into organised treatment spaces where access to healthcare is disrupted.',hero='visual-24-00',facts=[('Context','METU ID301 · Team project'),('Team','Öykü Çise Çancı, Tarık Bircan'),('Scope','Vehicle design, deployment & physical modelling')],sections=[
('research','Bring care closer.','The project responds to the difficulty of reaching healthcare in rural and disaster-affected areas. A transportable unit combines medical storage, treatment spaces and a deployment sequence within one vehicle concept.', [('visual-26-00','Early model: exploring the vehicle and expandable treatment volume'),('visual-26-03','Early exploration of the rear treatment space')],[(25,'Research and problem definition'),(26,'Initial volume and vehicle studies'),(27,'Initial renders')],[('Transport','Keep essential care spaces and equipment within a mobile unit.'),('Deploy','Expand the vehicle with opening panels, poles and curtains.'),('Organise','Separate treatment zones and keep supplies close to the work area.')]),
('development','Test the space at scale.','Physical mock-ups explore how the enclosed vehicle opens into a larger working environment. Building the model makes the relationships between panels, furniture and circulation visible before the final form is resolved.', [('visual-28-00','Early physical mock-up in its compact configuration','photo'),('visual-28-02','Mock-up with the treatment platform extended','photo')],[(28,'Initial mock-ups and development review')],[]),
('deployment','From vehicle to care space.','Side panels open, extensions slide forward, and stored curtains and poles define enclosed treatment areas. The proposal separates green and red zones to organise care according to the patient’s condition.', [('visual-33-01','Deployed vehicle with two treatment zones','dark'),('visual-33-02','Compact vehicle configuration and roof arrangement','dark')],[(29,'Deployment sequence and treatment scenario'),(30,'Interior organisation and technical views')],[]),
('details','A place for every essential.','Interior storage, a sink, examination surfaces and accessible supplies support the proposed workflow. The final physical model demonstrates how the vehicle, folding elements and treatment enclosures come together.', [('visual-32-06','Interior layout with examination space and storage'),('visual-32-07','Cabinets and privacy curtain'),('visual-34-01','Final physical model with the treatment zone deployed','photo'),('visual-34-00','Interior of the final physical model','photo')],[(31,'Equipment allocation and storage zones'),(32,'Interior design details'),(33,'Exterior design'),(34,'Final physical model')],[])
]),
dict(slug='prodesign',name='ProDesign',card_name='Stand Designs for Prodesign',tag='Retail, exhibition & hospitality spaces',short='Brand experiences translated into physical spaces.',desc='A selection of stand, pop-up store and café concepts developed during my internship at ProDesign.',hero='visual-39-00',facts=[('Context','ProDesign · Design internship'),('Projects','Alsancak Café, Puma & Rioba'),('Scope','Spatial concepts, brand expression & visualisation')],sections=[
('alsancak','Alsancak Café','A warm, welcoming café exterior that gives people a place to pause. Lighting, seating and a continuous canopy create a coherent street-facing environment.', [('visual-37-00','Alsancak Café: overall exterior concept','photo'),('visual-37-02','Canopy, lighting and outdoor seating','photo')],[(37,'Alsancak Café concept presentation')],[]),
('puma','Puma pop-up store','An alternative pop-up retail proposal brings Puma’s athletic identity into a compact, modular format for shopping malls. Product display, bold graphics and an open structure establish a recognisable presence within a shared retail environment.', [('visual-38-00','Initial modular Puma pop-up concept'),('visual-38-02','Product display and circulation in the initial proposal')],[(38,'Initial Puma pop-up presentation')],[]),
('refinement','Developing the retail experience.','The final version was refined in response to brand feedback, with attention to visibility, function and the shopping mall setting. An open perimeter and integrated display areas organise the visitor’s experience.', [('visual-39-00','Final Puma concept in an exhibition setting','photo'),('visual-39-03','Integrated product display and brand communication','photo')],[(39,'Final Puma pop-up proposal')],[]),
('rioba','Rioba festival stand','A coffee festival stand that balances an inviting counter with a clear brand presence. The roof structure frames the space, while open shelving and faceted front details shape the visitor-facing side.', [('visual-40-00','Rioba stand: overall design proposal'),('visual-40-02','Rioba stand: alternate view and counter arrangement')],[(40,'Rioba stand presentation')],[])
])]

from detailed_content import enrich
enrich(projects)

header='<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="index.html#home">MERTCAN AYDOĞMUŞ</a><nav aria-label="Main navigation"><a href="index.html#about">About</a><span aria-hidden="true">/</span><a href="index.html#projects" aria-current="page">Projects</a><span aria-hidden="true">/</span><a href="resume.html">Resume</a><span aria-hidden="true">/</span><a href="mailto:m.aydogmus58@gmail.com" data-contact>Contact</a></nav></header>'
footer='<footer class="product-footer wrap"><p>© 2026 Mertcan Aydoğmuş</p><a href="mailto:m.aydogmus58@gmail.com">Let’s talk about design</a><a href="#main" class="back-top-link">Back to top ↑</a></footer>'
def document(title,description,body,cls):
    return f'<!doctype html>\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{e(description)}"><title>{e(title)} — Mertcan Aydoğmuş</title><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="product.css"><script src="script.js" defer></script><script src="product.js" defer></script></head><body class="{cls}">{header}{body}{footer}</body></html>'
cards=''
for p in projects:
    cards+=f'<article class="work-tile"><a href="{p["slug"]}.html"><div class="work-photo"><img src="assets/{p.get("card",p["hero"])}.webp" alt="{e(p["short"])}" loading="lazy"></div><div class="work-info"><div><h2>{p.get("card_name",p["name"])}</h2><p>{p["short"]}</p><span class="work-kind">{e(p["tag"])}</span></div><span class="open-icon" aria-hidden="true">↗</span></div></a></article>'
(root/'projects.html').write_text('<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0; url=index.html#projects"><title>Projects — Mertcan Aydoğmuş</title></head><body><p><a href="index.html#projects">View product design projects</a></p></body></html>',encoding='utf-8')
for i,p in enumerate(projects):
    nextp=projects[(i+1)%len(projects)]
    facts=''.join(f'<div><span>{a}</span>{e(b)}</div>' for a,b in p['facts'])
    nav=''.join(f'<a href="#{s[0]}">{ {"research":"Research","development":"Development","interface":"Interface","details":"Design details","layout":"Layout","deployment":"Deployment","alsancak":"Alsancak Café","puma":"Puma concept","refinement":"Puma final","rioba":"Rioba"}.get(s[0],s[0].replace("-"," ").title())}</a>' for s in p['sections'])
    content=''.join(section(*s) for s in p['sections'])
    body=f'<main id="main"><div class="case-intro wrap"><a class="breadcrumb" href="index.html#projects">← All projects</a><div class="case-title-row"><h1>{p["name"]}</h1><p class="summary">{p["desc"]}</p></div><div class="project-facts">{facts}</div></div><div class="feature-cover {p["slug"]}"><img src="assets/{p["hero"]}.webp" alt="{e(p["short"])}" fetchpriority="high"></div><nav class="study-nav" aria-label="Project sections"><div class="wrap"><a class="study-name" href="#main">{p["name"]}</a>{nav}</div></nav><div class="wrap">{content}</div><div class="next-work"><a class="wrap" href="{nextp["slug"]}.html"><div><small>Next project</small><h2>{nextp["name"]}</h2></div><span class="open-icon" aria-hidden="true">↗</span></a></div></main>'
    (root/f'{p["slug"]}.html').write_text(document(p['name'],p['desc'],body,'product-case'),encoding='utf-8')
print('Built project index and four case studies.')

# Reserve each image's layout space before lazy loading to keep section anchors stable.
import re
from PIL import Image
for slug in ['projects']+[p['slug'] for p in projects]:
    page=root/f'{slug}.html'
    html=page.read_text(encoding='utf-8')
    def size_image(match):
        tag=match.group(0)
        source=re.search(r'src="([^"]+)"',tag).group(1)
        if source.endswith('.svg'):
            import xml.etree.ElementTree as ET
            attrs=ET.parse(root/source).getroot().attrib
            w,h=int(attrs['width']),int(attrs['height'])
        else:
            with Image.open(root/source) as image:
                w,h=image.size
        return tag[:-1]+f' width="{w}" height="{h}" style="--asset-max:{w}px">'
    html=re.sub(r'<img\b[^>]*>',size_image,html)
    page.write_text(html,encoding='utf-8')
